#!/usr/bin/python3
import sys
from math import sqrt

if len(sys.argv) != 2:
    print('Usage: factors <file>')
    sys.exit(1)
file =  open(sys.argv[1], "r")

for line in file:
    number = int(line)
    n = int(sqrt(number)) + 1
    for p in range(2, n):
        if number % p == 0:
            q = number // p
            print(f"{number}={q}*{p}")
            break
        elif number % n == 0:
            q = number // n
            print(f"{number}={q}*{n}")
            break
        n -= 1
file.close()
